### ISSUE TITLE
Uncaught ReferenceError: filePath is not defined

### ISSUE THREAD

**Issue by ya-kostik** [mark-adams/open-on-bitbucket#13]
When I try to open а file in Bitbucket by cmd+shift+p command, this issue occurs

**Atom Version**: 1.12.6
**Electron Version**: 1.3.9
**System**: Mac OS X 10.12.1
**Thrown From**: [open-on-bitbucket](https://github.com/mark-adams/open-on-bitbucket) package, v0.4.0

### Stack Trace

Uncaught ReferenceError: filePath is not defined

```
At /Users/Constantin/.atom/packages/open-on-bitbucket/lib/bitbucket-file.coffee:15

ReferenceError: filePath is not defined
    at new BitbucketFile (/Users/Constantin/.atom/packages/open-on-bitbucket/lib/bitbucket-file.coffee:15:45)
    at Function.module.exports.BitbucketFile.fromPath (/Users/Constantin/.atom/packages/open-on-bitbucket/lib/bitbucket-file.coffee:11:9)
    at atom-pane.open-on-bitbucket:file (/Users/Constantin/.atom/packages/open-on-bitbucket/lib/main.coffee:14:25)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:210:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:04.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  4x -0:02.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:00.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.1.0 open-on-bitbucket:file (atom-text-editor.editor)
```

**Comment by ya-kostik** [comment]
You missed «@» on the line 15, before filePath variable

**Comment by jarecsni** [comment]
Same issue here with a fresh install of Atom & open-on-bitbucket project, nothing works, getting this same exception for any menu item.

**Comment by ya-kostik** [comment]
Hi, @jarecsni! You can fix it by yourself.
Just open 
~/.atom/packages/open-on-bitbucket/lib/bitbucket-file.coffee:15 in atom, and add missed «@» before filePath.

![2016-12-17 12 45 40](https://cloud.githubusercontent.com/assets/12064332/21285908/c56d9002-c456-11e6-8ec2-2c6704df2d05.png)

**Comment by jarecsni** [comment]
Ah thanks! Will do that now as an interim solution until it's fixed in the package, thank you!

**Comment by AdonisInveste** [comment]
I tried it but it is still giving the error

**Comment by Graahf** [comment]
Same here, tried adding @ before filepath, but no such luck getting it to work :(

**Comment by ya-kostik** [comment]
@Graahf, did you restart atom after change `~/.atom/packages/open-on-bitbucket/lib/bitbucket-file.coffee:15`?

**Comment by Graahf** [comment]
Aaaahhh that helped :)

nice, thx

**Comment by Encr1pt3d** [comment]
I don't know where is the error, this errors appears to me too. I have installed atom and i have put the open-bitbucket package. Then I opened a document and used ctr+shift+p and put bitbucket open repository. But the result is nothing...
Error:
[image](https://cloud.githubusercontent.com/assets/7103591/25127858/cf127622-2437-11e7-8eaa-0a971aab542f.png)

Code of bitbucket-file.coffee
![image](https://cloud.githubusercontent.com/assets/7103591/25127877/e0843468-2437-11e7-8452-c150d9673ab1.png)

I can't work with atom if this problem don't solve, please help me to work with bitbucket.

**Comment by roddypratt** [comment]
This Issue is marked as closed, but the version of the package that's downloaded by Atom still has the problem (and the missing '@' sign...)
