### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by kunalrrv** [mark-adams/open-on-bitbucket#16]
1.When i open the repo and click on Packages -> open on bitbucket -> then select any option.

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [open-on-bitbucket](https://github.com/mark-adams/open-on-bitbucket) package 0.5.0

### Stack Trace

Uncaught TypeError: Cannot read property '0' of null

```
At C:\Users\kunal\.atom\packages\open-on-bitbucket\lib\bitbucket-file.coffee:208

TypeError: Cannot read property '0' of null
    at BitbucketFile.module.exports.BitbucketFile.stashRepoUrlRepoUrl (/packages/open-on-bitbucket/lib/bitbucket-file.coffee:208:6)
    at BitbucketFile.module.exports.BitbucketFile.bitbucketRepoUrl (/packages/open-on-bitbucket/lib/bitbucket-file.coffee:181:15)
    at BitbucketFile.module.exports.BitbucketFile.validationErrors (/packages/open-on-bitbucket/lib/bitbucket-file.coffee:96:13)
    at BitbucketFile.module.exports.BitbucketFile.isOpenable (/packages/open-on-bitbucket/lib/bitbucket-file.coffee:86:6)
    at BitbucketFile.module.exports.BitbucketFile.blame (/packages/open-on-bitbucket/lib/bitbucket-file.coffee:36:9)
    at /packages/open-on-bitbucket/lib/main.coffee:22:44)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.21.1/resources/app/src/command-registry.js:381:36)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.21.1/resources/app/src/command-registry.js:266:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.21.1/resources/app/src/atom-environment.js:1348:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.21.1/resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:41.1.0 open-on-bitbucket:repository (atom-pane.pane.active)
     -1:34.9.0 open-on-bitbucket:branch-compare (div.tool-panel.tree-view)
     -1:17.6.0 open-on-bitbucket:blame (input.hidden-input)
```

### Non-Core Packages

```
open-on-bitbucket 0.5.0 
```

**Comment by mcmegavolt** [comment]
The same issue on Ubuntu 16.04
